# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 07:50
# from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newauction',
            name='auctionDeadline',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newauction',
            name='auctionPrice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
