# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 18:22
# from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Yaas', '0002_auto_20170926_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='newauction',
            name='auctionSeller',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newauction',
            name='auctionCreationTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='newauction',
            name='auctionDeadline',
            field=models.DateTimeField(),
        ),
    ]
