# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 08:37
# from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaas', '0003_auto_20171004_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='newauction',
            name='auctionBan',
            field=models.BooleanField(default=False),
        ),
    ]
