# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaas', '0006_auto_20180109_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setuserlang',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='setuserlang',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='newauction',
            name='setLan',
            field=models.CharField(default=b'en', max_length=3),
        ),
        migrations.DeleteModel(
            name='setUserLang',
        ),
    ]
