# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yaas', '0007_auto_20180110_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setUserLang', models.CharField(default=b'en', max_length=3)),
                ('setUserId', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='newauction',
            name='setLan',
        ),
    ]
